### PR TITLE
Migrate to v5

### PR DESCRIPTION
**Pull request by helfi92**

### CODE REVIEW

**Comment by helfi92** [comment]
When I make changes in app.js, HMR works as expected. When I make changes in index.js, I get the following error:

```bash
[HMR] Cannot apply update.
[HMR] Error: Aborted because ./src/index.js is not accepted
Update propagation: ./src/index.js -> 1
    at hotApply (/Users/hassanali/Documents/Mozilla/projects/node-starter/build/index.js:394:30)
    at hotUpdateDownloaded (/Users/hassanali/Documents/Mozilla/projects/node-starter/build/index.js:247:13)
    at hotAddUpdateChunk (/Users/hassanali/Documents/Mozilla/projects/node-starter/build/index.js:227:13)
    at hotDownloadUpdateChunk (/Users/hassanali/Documents/Mozilla/projects/node-starter/build/index.js:5:12)
    at hotEnsureUpdateChunk (/Users/hassanali/Documents/Mozilla/projects/node-starter/build/index.js:237:13)
    at /Users/hassanali/Documents/Mozilla/projects/node-starter/build/index.js:208:14
[HMR] You need to restart the application!
```
Is that normal?

**Comment by eliperelman** [comment]
@helfi92 is your issue resolved? Looks like the code is different to only accept `app.js`.

**Comment by helfi92** [comment]
@eliperelman The code should only refresh when I change `app.js`. Right now If I make a change inside `index.js`, I expect nothing to happen but I get an error basically saying that HMR within `index.js` is not accepted which is what I expect in the first place but I'm not sure why I am getting this error. I wonder why it's aborting.

**Comment by eliperelman** [comment]
I think that is to be expected. If you want to make a change to the index.js file, but it's not being accepted, you have to kill the process in order to get the index.js change.

**Pull request merged**
